version: '3.9'

services:
  backend:
    image: golang:1.20
    ports:
      - "80:80"
    volumes: 
      - .:/app
    working_dir: /app
    command: ["go", "run", "main.go"]
  db:
    image: postgres:15.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password